SQUAT:
  MAIN:
    GREEN: "Back Squat"
    ORANGE: "Box Squat (Vertical Shin)"
  ACCESSORY:
    GREEN: "SL Knee Extension"
    ORANGE: "SL Knee Extension Isometric"

HINGE:
  MAIN:
    GREEN: "BB RDL"
    ORANGE: "BB RDL" # Or Trap Bar
  ACCESSORY_HIP:
    GREEN: "DB SL RDL"
    ORANGE: "DB SL RDL"
  ACCESSORY_KNEE:
    GREEN: "SL Leg Curl"
    ORANGE: "SL Leg Curl"

PUSH:
  MAIN:
    GREEN: "BB Bench Press"
    ORANGE: "Incline DB Press"
  ACCESSORY_VERTICAL:
    GREEN: "Half-kneeling DB OH Press"
    ORANGE: "Half-kneeling DB OH Press"
  ACCESSORY_HORIZONTAL:
    GREEN: "Incline DB Press"
    ORANGE: "Push Up"

PULL:
  MAIN:
    GREEN: "Chin Up"
    ORANGE: "Lat Pulldown"
  ACCESSORY_VERTICAL:
    GREEN: "Lat Pulldown"
    ORANGE: "Lat Pulldown"
  ACCESSORY_HORIZONTAL:
    GREEN: "Chest-supported DB Row"
    ORANGE: "Chest-supported DB Row"

LUNGE:
  ACCESSORY:
    GREEN: "DB Bulgarian Split Squat"
    ORANGE: "Lunge Isometric Hold"

CORE:
  TRANSVERSE:
    GREEN: "Half-kneeling Cable Rotation"
    ORANGE: "Half-kneeling Cable Rotation"
  SAGITTAL:
    GREEN: "Hanging Knee Tuck"
    ORANGE: "Hanging Knee Tuck"
  FRONTAL:
    GREEN: "DB Side Bend"
    ORANGE: "DB Side Bend"

PATELLAR_ISO:
  PREP:
    GREEN: "SL Wall Sit"
    ORANGE: "SL Wall Sit"

RFD:
  HIGH:
    - "Hurdle Jump"
    - "Hang Power Clean"
  LOW:
    - "Box Jump"
    - "Snatch Grip High Pull"
  UPPER:
    - "MB Chest Pass"
    - "MB Rotational Throw"
