# Format: CATEGORY -> PATTERN -> (STATE or DEFAULT)

SQUAT:
  MAIN: # RED is omitted; the Template for RED days simply won't call SQUAT:MAIN
    GREEN:
      - "Back Squat"
    ORANGE: 
      - "Box Squat (Vertical Shin)"
  ACCESSORY:
    GREEN:
      - "SL Knee Extension"
    ORANGE:
      - "SL Knee Extension Iso"

HINGE:
  MAIN:
    DEFAULT:
      - "BB RDL"
  ACCESSORY_HIP:
    DEFAULT:
      - "DB SL RDL"
  ACCESSORY_KNEE:
    DEFAULT:
      - "SL Leg Curl"

PUSH:
  MAIN: # Knee/Energy doesn't change the movement, just the load
    DEFAULT:
      - "BB Bench Press"
  ACCESSORY_HORIZONTAL:
    DEFAULT:
      - "Incline DB Press"
  ACCESSORY_VERTICAL:
    DEFAULT:
      - "Half-kneeling DB OH Press"

PULL:
  MAIN:
    DEFAULT:
      - "Chin Up"
  ACCESSORY_VERTICAL:
    DEFAULT:
      - "Lat Pulldown"
  ACCESSORY_HORIZONTAL:
    DEFAULT:
      - "Chest-supported DB Row"

RFD:
  HIGH:
    DEFAULT:
      - "Hurdle Jump"
      - "Hang Power Clean"
  LOW:
    DEFAULT:
      - "Box Jump"
      - "Snatch Grip High Pull"
  UPPER:
    DEFAULT: # Only called on RED days per logic.yaml
      - "MB Chest Pass"
      - "MB Rotational Throw"

CORE:
  TRANSVERSE:
    DEFAULT:
      - "Half-kneeling Cable Rotation"
  SAGITTAL:
    DEFAULT:
      - "Hanging Knee Tuck"
  FRONTAL:
    DEFAULT:
      - "DB Side Bend"

ISOMETRIC:
  PATELLAR:
    DEFAULT:
      - "SL Knee Extension Iso"
  HAMSTRING:
    DEFAULT:
      - "SL Foam Roller Hamstring Iso"

MOBILITY:
  DYNAMIC:
    DEFAULT:
      - "Inchworms"
      - "World's Greatest Stretch"
      - "Cat Cow"
      - "Hip Flexor Stretch"
      - "Pigeon Stretch"
